### ISSUE TITLE
Pratica 3_bizagi

### ISSUE THREAD

**Issue by ka194** [SistemasTecTlaxiaco/actividad-6-proceso-de-negocio-en-bizagi-proyecto-ka194#1]
[Practia 3 de modelo Bizagi.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-proceso-de-negocio-en-bizagi-proyecto-ka194/files/12825960/Practia.3.de.modelo.Bizagi.pdf)

**Comment by YaelStO** [comment]
Buen trabajo 18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
